//
//  IntroductionText.swift
//  BAKCO VanKhang
//
//  Created by Kiet on 4/18/18.
//  Copyright © 2018 Lou. All rights reserved.
//

import Foundation


struct MyIntroductionText {
    
    static let contactInformation = "THÔNG TIN LIÊN HỆ \nCÔNG TY TNHH GIẢI PHÁP SỨC KHỎE VẠN KHANG\n(VAN KHANG HEALTH SOLUTIONS JOINT STOCK COMPANY)\nĐịa chỉ: 31A/8 Hùng Vương, P9, Q5, TPHCM\nHotline: 1900 63 66 71\nMST: 0314538127\nWebsite: www.vkhealth.vn\n\nTHỜI GIAN LÀM VIỆC - BỘ PHẬN VĂN PHÒNG\nVăn phòng VKHS : (028) 7300 2246\nVăn phòng  SOS  :  (028) 7300 2611\nTừ thứ hai đến thứ bảy hàng tuần (trừ các ngày Lễ).\nBuổi sáng: 8h00 đến 12h00.\nBuổi chiều: 13h00 đến 17h00."
    
    static let sosIntroduction = "GỌI CẤP CỨU SOS\nBệnh tật và tai nạn là rủi ro không của riêng ai nên được cấp cứu, chữa trị kịp thời là nhu cầu bức thiết của mọi người.\n\nHiện nay, khi xảy ra sự cố cần cấp cứu, người dân còn gặp nhiều khó khăn để có thể tiếp nhận được dịch vụ cấp cứu chuyên nghiệp nên thường phải tự xử lý và tự vận chuyển người bệnh đến bệnh viện, thường không đúng kỹ thuật chuyên môn y tế dẫn đến nhiều hậu quả đáng tiếc.\n\nPhản ứng nhanh – Tận dụng thời gian vàng trong cấp cứu – Thực hiện cấp cứu hiệu quả luôn là mong muốn của mọi người.\n\nThấu cảm nỗi lo và mong ước ấy, Trung tâm cấp cứu Vạn Khang SOS (đơn vị trực thuộc Công ty Giải pháp sức khỏe Vạn Khang) triển khai cung ứng dịch vụ cấp cứu tại chỗ cho người dân TP.HCM theo một mô hình mới:\nKhông cần số điện thoại gọi cấp cứu, khi có yêu cầu cấp cứu, chỉ cần bấm nút SOS sẽ được đáp ứng ngay. Bác sĩ gần nhất sẽ được điều động, phương tiện phù hợp nhất sẽ được sử dụng để tiếp cận bệnh nhân trong thời gian sớm nhất có thể\nKhông chỉ có ô tô cấp cứu, Vạn Khang SOS còn sẵn sàng mô tô cấp cứu để có thể tiếp cận nhanh nhất với người bệnh, nhất là trong tình trạng tắt đường hoặc nhà trong hẻm sâu. Xe mô tô được trang bị đầy đủ thiết bị cấp cứu như trên xe ô tô, kể cả máy điện tim, shock tim… để thực hiện cấp cứu tại chỗ hiệu quả. Xe mô tô không vận chuyển bệnh nhân.\nLiên kết các bệnh viện để thiết lập mạng lưới cấp cứu chuyên nghiệp được phân bố đều khắp trên địa bàn thành phố nhằm đáp ứng nhanh nhất yêu cầu cấp cứu của người dân (Xem thêm...)\nỨng dụng công nghệ thông tin tiên tiến để quản lý, vận hành hệ thống tự động giúp tiếp cận nhanh chóng, cấp cứu hiệu quả cho người bệnh.\nĐể sử dụng dịch vụ cấp cứu tại chỗ:\nHãy tải miễn phí “Ứng dụng VKHEALTH”  www.vkhealth.vn sẵn sàng\nKhi có yêu cầu cấp cứu, chỉ cần bấm nút “SOS” trên “Ứng dụng VKHEALTH”, tổng đài tự động sẽ định vị người bệnh và điều động xe cấp cứu gần nhất đang trong tình trạng sẵn sàng để thực hiện nhiệm vụ.\n\nTrường hợp chưa có “Ứng dụng VKHEALTH”, Bạn có thể liên hệ với Trung tâm diều hành Vạn Khang SOS qua số 1900 63 66 71 để được phục vụ cấp cứu tại chỗ."
    
    static let teleHealth = "\nTelehealth là hệ thống tư vấn chăm sóc sức khỏe từ xa cho bạn và gia đình bạn.\nTrong tất cả các tình huống y tế tại nhà không khẩn cấp bạn và gia đình bạn sẽ được chính các Bác sĩ chuyên khoa hàng đầu đưa ra lời khuyên, lời hướng dẫn y tế thông qua hệ thống Hội nghị truyền hình Y khoa chuyên dụng.\nTelehealth tương tác 2 bên bằng hình ảnh và âm thanh trong thời gian thực, qua đó  BS đánh giá được tổng trạng của tình huống y tế hiện tại, BS có thể có được chẩn đoán ban đầu giúp việc tư vấn và hướng dẫn cho bạn xử lý tình huống chính xác hơn. Thậm chí nếu cần thiết phải đến bệnh viện thì BS cũng sẽ hướng dẫn chính xác cho bạn cần phải khám ở chuyên khoa nào để tránh mất thời gian của bạn.\nNgoài sự tương tác 2 bên bằng hình ảnh và âm thanh, hệ thống Telehealth còn cho phép BS xem lại các hồ sơ y tế của bạn. Khi bạn đã có hồ sơ khám chữa bệnh lưu trữ trên cloud VKHEALTH thì việc tham khảo các dữ liệu y tế sẵn có như kết quả chẩn đoán những lần khám bệnh trước đó, kết quả xét nghiệm, chụp phim, siêu âm vv… giúp BS có được chẩn đoán ban đầu chính xác hơn để việc tư vấn, hướng dẫn đạt hiệu quả hơn.\nTrong phiên kết nối tư vấn chăm sóc sức khỏe từ xa khi BS nhận thấy cần có thêm ý kiến của Chuyên gia, BS sẽ mời Chuyên gia cùng tư vấn và giải đáp mọi thắc mắc theo yêu cầu của bạn"
    
    static let booking = "\nĐĂNG KÝ KHÁM BỆNH HẸN GIỜ VÀ THANH TOÁN\nBạn phải chờ đợi suốt 3 – 4h khi đi khám bệnh để chỉ được khám, xét nghiệm, chụp phim… không đến 30 phút!\nBạn phải chờ đợi nhiều giờ trong bầu không khí bệnh viện nghẹt người vì quá tải, với nguy cơ bị lây nhiễm bệnh từ người khác!\nTất cả những nổi khỗ mà bạn đang phải chịu đựng sẽ không còn nữa khi bạn sử dụng dịch vụ “Đăng ký khám bệnh” của VKHS.\nBạn chỉ cần nhấn vào biễu tượng “Đăng ký khám bệnh” trên Ứng dụng hoặc trên web VKHS rồi chọn lựa các thông tin theo yêu cầu khám bệnh của bạn:\n\tKhám bệnh cho chính bạn hay người khác \n\tKhám ở BV/ PK nào \n\tCó sử dụng BHYT hay không \n\tKhám thông thường hay khám dịch vụ hay chọn lựa chuyên gia và ngày giờ khám \n\tChuyên khoa khám: có thể là Phòng khám Nội tổng hợp hoặc các phòng khám chuyên khoa hoặc các dịch vụ kỹ thuật như xét nghiệm, chụp Xquang, CT… hay Siêu âm, Nội soi…\nHệ thống sẽ gởi đến thiết bị của bạn “Lịch hẹn khám bệnh” với đủ thông tin cần thiết: Số thứ tự, giờ hẹn khám bệnh, phòng khám bệnh…\nBạn có thể thanh toán trước cho bệnh viện: Nhấn vào nút thanh toán trên web/Ứng dụng VKHS.\nTrường hợp bạn đã đến BV/PK, nhân viên BV/PK sẽ hướng dẫn bạn thực hiện “Đăng ký khám bệnh” trên “màn hình cảm ứng” giống như trên web/Ứng dụng VKHS, đồng thời sẽ giúp bạn tải Ứng dụng VKHS và lập Thẻ ngân hàng Vietin - VKHS.\nNgười đã tải Ứng dụng và lập Thẻ ngân hàng Vietin – VKHS được hưởng rất nhiều quyền lợi"
    
    
    static let familyDoctor = "\nBạn hoặc người thân cần được chăm sóc, chữa trị bệnh nhưng chưa thật sự cần thiết phải vào bệnh viện để phải chịu đựng sự mệt mỏi vì chen chúc, đợi chờ và gánh chịu những nguy cơ bị lây nhiễm bệnh khác.\nPhòng khám Bác sĩ gia đình Vạn Khang SOS (đơn vị trực thuộc Công ty Giải pháp sức khỏe Vạn Khang) cung ứng cho bạn dịch vụ chăm sóc sức khỏe toàn diện tại nhà trên địa bàn TP.HCM:\n\tBác sĩ đến khám bệnh, kê đơn điều trị, tư vấn điều trị và chăm sóc sức khỏe\n\tĐiều dưỡng đến chăm sóc người bệnh: tiêm chích, thay băng, chăm sóc vết thương…\n\tKỹ thuật viên đến tập vật lý trị liệu và hướng dẫn người bệnh tập vật lý trị liệu.\n\tBác sĩ, Lương y đến khám bệnh, tư vấn điều trị và thực hiện chữa bệnh tại nhà theo Y học cổ truyền\n\tBác sĩ, Điều dưỡng, Kỹ thuật viên đến thực hiện chăm sóc giảm nhẹ (chống đau, giảm khó thở…) cho bệnh nhân ung thư giai đoạn cuối, bệnh nhân nặng…\n\tCung cấp thuốc điều trị, lấy mẫu bệnh phẩm để xét nghiệm tại nhà theo chỉ định của Bác sĩ.\n\tCác dịch vụ khác theo yêu cầu.\nBên cạnh đó, Vạn Khang SOS còn cung cấp dịch vụ vận chuyển bệnh nhân khi có nhu cầu:\n\tVận chuyển bệnh nhân đến bệnh viện, phòng khám để khám chữa bệnh, được liên hệ trước để giảm chờ đợi\n\tChuyển viện hoặc đưa bệnh nhân từ bệnh viện, phòng khám về nhà.\nVạn Khang SOS ứng dụng công nghệ cao, tự động tạo sự tiện dụng cho khách hàng, cho cán bộ y tế luôn sẵn sàng đáp ứng yêu cầu chăm sóc, khám chữa bệnh tại nhà\nĐể sử dụng dịch vụ chữa bệnh tại nhà, Bạn có thể:\n-Tải miễn phí “Ứng dụng VKHEALTH” www.vkhealth.vn\nKhi có yêu cầu dịch vụ, chỉ cần bấm vào biểu tượng của dịch vụ yêu cầu trên “Ứng dụng VKHS”, tổng đài tự động chuyển thông tin đến cán bộ y tế (BS, Điều dưỡng, Kỹ thuật viên) gần nhà bệnh nhân nhất để thống nhất lịch hẹn thực hiện nhiệm vụ.\n-Trường hợp chưa có “Ứng dụng VKHEALTH”, Bạn có thể:\n\t+ Yêu cầu dịch vụ từ trang web www.vkhealth.vn hoặc\n\t+ Liên hệ với Trung tâm diều hành Vạn Khang SOS qua số 1900 63 66 71 để được phục vụ."
}













